# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "dlv debug --headless --listen=:2345 --api-version=2 --log"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = []
include_dir = []
kill_delay = "1000ms"
stop_on_error = true
send_interrupt = true
log = "build-errors.log"

[color]
app = ""
build = "yellow"
runner = "green"

[log]
time = false
level = "debug"
