FROM golang:1.20 as builder

WORKDIR /go/src

RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ENV GO111MODULE=on

COPY go.mod go.sum ./

RUN go mod download

ENV DOTENV_PATH=/go/src/.env

CMD ["dlv", "debug", "--headless", "--listen=:2345", "--api-version=2", "--log"]
