swagger: '2.0'
info:
  title: Semi Systems API
  description: API for Semi Systems
  version: 1.0.0
host: localhost
schemes:
  - http
basePath: /
produces:
  - application/json

paths:
  /user/login:
    post:
      summary: User Login
      description: Login a user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserLogin'
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/LoginResponse'
        400:
          description: Invalid input

  /user/refresh-token:
    post:
      summary: Refresh Token
      description: Refresh authentication token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserRefreshToken'
      responses:
        200:
          description: Successful token refresh
        400:
          description: Invalid input

  /user/me:
    get:
      summary: Get Current User
      description: Returns data of the current user
      responses:
        200:
          description: User information
          schema:
            $ref: '#/definitions/User'

  /articles:
    get:
      summary: Get All Articles
      description: Returns all articles
      responses:
        200:
          description: An array of articles
          schema:
            type: array
            items:
              $ref: '#/definitions/Article'

definitions:
  UserLogin:
    type: object
    required:
      - name
      - password
    properties:
      session:
        type: boolean
      name:
        type: string
      password:
        type: string

  UserRefreshToken:
    type: object
    required:
      - refresh_token
    properties:
      session:
        type: boolean
      refresh_token:
        type: string

  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string

  Article:
    type: object
    properties:
      id:
        type: integer
      author_id:
        type: integer
      author:
        type: string
      title:
        type: string
      text:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string
