swagger: '2.0'
info:
  title: Semi Systems API
  description: API for Semi Systems
  version: 1.0.0
host: localhost
schemes:
  - http
basePath: /
produces:
  - application/json

paths:
  # User-related paths
  /user/login:
    post:
      summary: User Login
      description: Login a user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserLogin'
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/UserLoginResponse'
        400:
          description: Invalid input

  /user/refresh-token:
    post:
      summary: Refresh Token
      description: Refresh authentication token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserRefreshToken'
      responses:
        200:
          description: Successful token refresh
          schema:
            $ref: '#/definitions/UserLoginResponse'
        400:
          description: Invalid input

  /user/me:
    get:
      summary: Get Current User
      description: Returns data of the current user
      responses:
        200:
          description: User information
          schema:
            $ref: '#/definitions/User'

  # Article-related paths
  /articles:
    post:
      summary: Create Article
      description: Create a new article
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ArticleCreate'
      responses:
        200:
          description: Article created successfully
          schema:
            $ref: '#/definitions/Article'

  /articles/{id}:
    put:
      summary: Update Article
      description: Update an existing article
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ArticleUpdate'
      responses:
        200:
          description: Article updated successfully
          schema:
            $ref: '#/definitions/Article'

definitions:
  UserLogin:
  # ... (User Login definition)
  UserRefreshToken:
  # ... (User Refresh Token definition)
  UserLoginResponse:
  # ... (User Login Response definition)
  User:
  # ... (User definition)
  Article:
    type: object
    properties:
      id:
        type: integer
      author_id:
        type: integer
      author:
        type: string
      title:
        type: string
      text:
        type: string
  ArticleCreate:
    type: object
    required:
      - author_id
      - title
      - text
    properties:
      author_id:
        type: integer
      title:
        type: string
      text:
        type: string
  ArticleUpdate:
    type: object
    required:
      - id
      - title
      - text
    properties:
      id:
        type: integer
      title:
        type: string
      text:
        type: string
